### ISSUE TITLE
Path format is not documented

### ISSUE THREAD

**Issue by dolmen** [romshark/jscan#12]
The format for paths returned by [Iterator.Path](https://pkg.go.dev/github.com/romshark/jscan#Iterator.Path) and [IteratorBytes.Path](https://pkg.go.dev/github.com/romshark/jscan#IteratorBytes.Path) is not documented. Is it JSON Pointer ([RFC 6901](https://tools.ietf.org/html/rfc6901))? Some other format?

**Comment by romshark** [comment]
The path was a tertiary feature that I didn't pay much attention to. It's not RFC compliant, it's just a custom format. I even thought about removing it because [tidwall/gjson](https://pkg.go.dev/github.com/tidwall/gjson) for example does a much better job at getting values by path, but I decided to still keep it in v1 because it was already working.
RFC compliance may only be possible in v2.

**Comment by romshark** [comment]
[v2.0](https://github.com/romshark/jscan/tree/jscan-v2) will feature [RFC-6901](https://datatracker.ietf.org/doc/html/rfc6901) JSON pointers.
